version: "2.2"
services:
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "4680:3000"
    volumes:
      - "/app/node_modules"
      - "./:/app"
